deployment:
    Example deployment:
        description: This is an example deployment to test jinja templates

        input:
            external_input: {
                type: raw_data,
                human_input: true
            }
                        
        output:
            validated_data: {
                type: data
            }
                        state_of_function: {
                type: error_code
            }
                        
        functions:
         - read_input_data
         - validate_raw_input
         